services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5439:5432"
    env_file:
      - ./postgres.env
    networks:
      - connector
  
  connector:
    build:
      context: .
    container_name: connector
    ports:
      - 8081:8081
    env_file:
      - ./connector.env
    networks:
      - connector
    depends_on:
      - postgres
    platform: linux/amd64


networks:
  connector: